channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - matplotlib=3.1.1
  - networkx>=2.4
  - nibabel>=2.3.1
  - nilearn>=0.4.2
  - nipype>=1.1.4
  - numpy>=1.16.2
  - pandas
  - pathos
  - pip=21.0.1
  - python=3.6.8
  - scikit-learn>=0.20.0
  - scipy
  - seaborn>=0.9.0
  - simpleitk>=2.0.2
  - tqdm
  - pip:
    - pybids==0.13
    - qbatch==2.2.1
